public with sharing class MyFirstClass {
    public void Method(){
        System.debug('Hello Class');
        System.debug('Hello Class');

    }
      public void Method2(){
        System.debug('Hello Class');
        System.debug('Hello Class');
        System.debug(1 +29);
        System.debug(1 +291);
        System.debug(1 +29);
        System.debug(1 +291);
         System.debug(1 +29);
        
  

        System.debug(1 +29);
         } 

}